" `home-manager` automatically loads `vim-sensible`, I don't want that. This is
" a workaround that prevents `vim-sensible` from being loaded.
let g:loaded_sensible = 'yes'

set nocompatible

set autoindent
set autoread
set backspace=indent,eol,start
set colorcolumn=+1
set formatoptions-=t
set hidden
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set list
set listchars=tab:→\ 
set nohlsearch
set nojoinspaces
set nowrap
set number
set ruler
set shortmess+=I
set smartcase
set spelllang=en_us,sl
set splitbelow
set splitright
set textwidth=80
set wildignore=*.o
set wildmenu

if has('gui_running')
  set guioptions-=m
  set guioptions-=T
  set guioptions-=r
  set guioptions-=L
  set guifont=DejaVu_Sans_Mono:h10
endif

syntax on
colorscheme saturnite
highlight ErrorMsg ctermbg=red

" Highlight trailing whitespace
match ErrorMsg '\s\+$'

" Some common typos
command! -bang -nargs=? -complete=file W w<bang> <args>
command! -bang -nargs=? -complete=file Wq wq<bang> <args>
command! -bang -nargs=? -complete=file WQ wq<bang> <args>
command! -bang Q q<bang>
command! -bang Qa qa<bang>
command! -bang QA qa<bang>

inoremap <C-c> <Esc>
noremap <silent> <F11> <Cmd>!ctags -R .<CR>

filetype plugin indent on

augroup MyAutoCommands
  autocmd!

  autocmd BufRead,BufNewFile *.h setl filetype=c
  autocmd FileType c setl cindent cino=:0,t0 noet sts=8 sw=8 ts=8
  autocmd FileType cpp setl cindent cino=:0,g0,l1,N-s et sts=2 sw=2 ts=2
  autocmd FileType css setl et sw=2 sts=2 ts=2
  autocmd FileType gitcommit setl spell
  autocmd FileType html setl et sw=2 sts=2 ts=2
  autocmd FileType python setl et sw=4 sts=4 ts=4
  autocmd FileType scss setl et sw=2 sts=2 ts=2
  autocmd FileType tex setl et sw=2 sts=2 ts=2
  autocmd FileType xml setl et sw=2 sts=2 ts=2
  autocmd FileType yaml setl et sw=2 sts=2 ts=2
augroup END
